INSERT INTO products (id, name, category, description, price, images)
VALUES
  -- A. Accessories (101 items)
  ('acc-001', 'Rattan 4-tier Chest', 'accessories', 'A functional 4-tier storage chest crafted from high-quality woven rattan, ideal for organizing living spaces with natural warmth.', 'Contact us', ARRAY['acc-001']),
  ('acc-002', 'Wicker and Cane 6 Drawer Chest', 'accessories', 'A spacious 6-drawer chest featuring natural cane webbing panels and a sturdy wicker frame for timeless bedroom storage.', 'Contact us', ARRAY['acc-002']),
  ('acc-003', 'Rattan Shelving Unit, 3-Tier', 'accessories', 'A versatile 3-tier rattan shelf unit designed to display books, plants, or decorative items with lightweight elegance.', 'Contact us', ARRAY['acc-003']),
  ('acc-004', 'Rattan 3-Tier Utility Organizer', 'accessories', 'A practical multi-purpose 3-tier rattan organizer, perfect for compact space organization in bedrooms or bathrooms.', 'Contact us', ARRAY['acc-004']),
  ('acc-005', 'Pineapple Rattan Wall Mirror', 'accessories', 'A playful pineapple-shaped rattan wall mirror that brings a whimsical tropical touch to modern wall decor.', 'Contact us', ARRAY['acc-005']),
  ('acc-006', 'Crescent Moon Rattan Mirror', 'accessories', 'An artistic crescent moon-shaped rattan frame surrounding a mirror, adding boho charm to nursery or bedroom walls.', 'Contact us', ARRAY['acc-006']),
  ('acc-007', 'Rattan Wall Hanger with Hooks', 'accessories', 'A handcrafted rattan wall coat rack featuring sturdy woven hooks for hanging coats, bags, or accessories.', 'Contact us', ARRAY['acc-007']),
  ('acc-008', 'Wicker Giraffe Standing Storage Unit', 'accessories', 'A charming giraffe-shaped standing storage basket handcrafted from wicker, perfect for kids rooms or nurseries.', 'Contact us', ARRAY['acc-008']),
  ('acc-009', 'Elephant Rattan Rocking Chair', 'accessories', 'A delightful elephant-shaped rattan rocker chair designed for nursery playroom seating and decor.', 'Contact us', ARRAY['acc-009']),
  ('acc-010', 'Wicker Rectangular Wall Mirror', 'accessories', 'A classic rectangular wall mirror framed with handwoven wicker detailing for subtle organic interior accenting.', 'Contact us', ARRAY['acc-010']),
  ('acc-011', 'Round Bear Rattan Floating Shelf', 'accessories', 'An adorable round floating shelf featuring bear-ear accents made of natural rattan, ideal for children rooms.', 'Contact us', ARRAY['acc-011']),
  ('acc-012', 'Large Rectangular Rattan Floor Mirror', 'accessories', 'A full-length floor mirror enclosed in a thick, handcrafted natural rattan frame for rustic elegance.', 'Contact us', ARRAY['acc-012']),
  ('acc-013', 'Sunburst Rattan Wall Mirror', 'accessories', 'A striking sunburst-patterned rattan mirror designed to serve as a bold accent focal point in living areas.', 'Contact us', ARRAY['acc-013']),
  ('acc-014', 'Wicker Storage Bench with Wheels', 'accessories', 'A versatile mobile wicker storage bench fitted with smooth rolling wheels for effortless organization.', 'Contact us', ARRAY['acc-014']),
  ('acc-015', 'Rounded Square Wicker Mirror', 'accessories', 'A modern soft-edged square wall mirror wrapped in handwoven natural wicker framing.', 'Contact us', ARRAY['acc-015']),
  ('acc-016', '2-Tier Rattan Serving Tray Stand', 'accessories', 'A two-tiered rattan tray stand featuring integrated carrying handles, perfect for entertaining or tea service.', 'Contact us', ARRAY['acc-016']),
  ('acc-017', 'Square Sunburst Rattan Mirror', 'accessories', 'A geometric square-framed wall mirror surrounded by radiant rattan spokes for dynamic wall art.', 'Contact us', ARRAY['acc-017']),
  ('acc-018', 'Flower Petal Rattan Mirror', 'accessories', 'A beautiful wall mirror surrounded by hand-shaped rattan flower petals, giving a cheerful botanical vibe.', 'Contact us', ARRAY['acc-018']),
  ('acc-019', 'Rocket-shaped Rattan Mirror', 'accessories', 'A creative rocket-shaped rattan frame surrounding a round mirror, designed to spark imagination in children spaces.', 'Contact us', ARRAY['acc-019']),
  ('acc-020', 'Fish-Shaped Rattan Wall Mirror', 'accessories', 'A nautical fish-contoured wall mirror crafted from bent natural rattan, suited for coastal-themed spaces.', 'Contact us', ARRAY['acc-020']),
  ('acc-021', 'Star-Shaped Rattan Wall Mirror', 'accessories', 'A decorative star-shaped wall mirror hand-formed from durable natural rattan strands.', 'Contact us', ARRAY['acc-021']),
  ('acc-022', 'Rainbow Rattan Wall Hanger with Hooks', 'accessories', 'A cheerful rainbow-arched rattan wall rack equipped with hanging pegs for kids apparel and accessories.', 'Contact us', ARRAY['acc-022']),
  ('acc-023', 'Minimalist Rattan Clothes Hanger', 'accessories', 'A lightweight yet durable individual clothes hanger handcrafted from solid steam-bent rattan.', 'Contact us', ARRAY['acc-023']),
  ('acc-024', 'Decorative Rattan Clothes Hanger', 'accessories', 'An artisan rattan garment hanger featuring interior geometric weave details for boutique display aesthetics.', 'Contact us', ARRAY['acc-024']),
  ('acc-025', 'Arched Rattan Wall Mirror', 'accessories', 'A sleek arched wall mirror featuring a clean, minimalist natural rattan outer frame.', 'Contact us', ARRAY['acc-025']),
  ('acc-026', 'Loop Rattan Flower Mirror', 'accessories', 'A looped rattan wall mirror shaped like a delicate blooming flower for bohemian wall styling.', 'Contact us', ARRAY['acc-026']),
  ('acc-027', 'Round Sunburst Rattan Mirror', 'accessories', 'A timeless circular wall mirror highlighted by outward-radiating natural rattan sunbeams.', 'Contact us', ARRAY['acc-027']),
  ('acc-028', 'Rattan Bird Wall Decor Set', 'accessories', 'A decorative set of bird-shaped woven rattan wall art pieces designed for playful wall accents.', 'Contact us', ARRAY['acc-028']),
  ('acc-029', 'Sunburst Woven Wall Baskets Set', 'accessories', 'A curated set of woven natural fiber wall baskets featuring intricate sunburst weave patterns.', 'Contact us', ARRAY['acc-029']),
  ('acc-030', 'Black & Natural Woven Wall Baskets Set', 'accessories', 'A set of handwoven decorative wall baskets showcasing contrasting black and natural dye patterns.', 'Contact us', ARRAY['acc-030']),
  ('acc-031', 'Cloud-shaped Rattan Wall Mirror', 'accessories', 'A soft cloud-contoured wall mirror framed in natural rattan, perfect for soothing nursery interiors.', 'Contact us', ARRAY['acc-031']),
  ('acc-032', 'Rattan Handheld Shaker', 'accessories', 'An eco-friendly, artisan-crafted handheld rattan shaker toy/rattle designed for infant play.', 'Contact us', ARRAY['acc-032']),
  ('acc-033', 'Minimalist Rattan Clothes Hanger 2', 'accessories', 'An alternative minimalist single-loop rattan clothes hanger designed for open wardrobe displays.', 'Contact us', ARRAY['acc-033']),
  ('acc-034', 'Octagonal Rattan Wall Mirror', 'accessories', 'An eight-sided octagonal wall mirror encircled by precision-bound natural rattan trim.', 'Contact us', ARRAY['acc-034']),
  ('acc-035', 'Square Wicker Mirror with Curved Corners', 'accessories', 'A square wall mirror featuring rounded corners bound in delicate woven natural wicker.', 'Contact us', ARRAY['acc-035']),
  ('acc-036', 'Oval Rattan Wall Mirror', 'accessories', 'An elegant oval-shaped wall mirror wrapped in smooth, continuous natural rattan tubing.', 'Contact us', ARRAY['acc-036']),
  ('acc-037', 'Burst Woven Wall Decor', 'accessories', 'A textured circular wall hanging woven from natural fibers to create a radiant focal accent.', 'Contact us', ARRAY['acc-037']),
  ('acc-038', 'Standing Banana Leaf Woven Decor Set', 'accessories', 'Sculptural standing accent pieces expertly handwoven using durable dried banana leaf fibers.', 'Contact us', ARRAY['acc-038']),
  ('acc-039', 'Fringed Woven Wall Hanging', 'accessories', 'A bohemian woven wall tapestry featuring soft raw fringe trimmings and textured weaving.', 'Contact us', ARRAY['acc-039']),
  ('acc-040', 'Rattan Baby Crib / Bassinet', 'accessories', 'A cozy, handcrafted rattan baby bassinet offering a safe, ventilated, and organic nursery bed.', 'Contact us', ARRAY['acc-040']),
  ('acc-041', 'Rattan Standing Baby Bassinet', 'accessories', 'A raised baby bassinet supported by an elegant, sturdy rattan frame structure.', 'Contact us', ARRAY['acc-041']),
  ('acc-042', 'Arched Rattan 4-Tier Bookshelf', 'accessories', 'A tall 4-tier bookshelf featuring a classic arched top frame and durable woven rattan shelves.', 'Contact us', ARRAY['acc-042']),
  ('acc-043', 'Rectangular Woven Tray Set with Handles', 'accessories', 'A set of rectangular nesting trays with woven bases and sturdy integrated side handles.', 'Contact us', ARRAY['acc-043']),
  ('acc-044', 'Round Rattan Serving Tray', 'accessories', 'A versatile round serving tray crafted with a raised woven rattan edge and sturdy base.', 'Contact us', ARRAY['acc-044']),
  ('acc-045', 'Cross-Legged Rattan Baby Bassinet', 'accessories', 'A stylish infant bassinet supported by an X-shaped cross-legged natural rattan stand.', 'Contact us', ARRAY['acc-045']),
  ('acc-046', 'Tall Arched Rattan Floor Mirror', 'accessories', 'A grand full-length floor mirror featuring an elegant arched top crafted from solid rattan.', 'Contact us', ARRAY['acc-046']),
  ('acc-047', 'Rattan Nursery Crib with Mattress', 'accessories', 'A full nursery infant crib crafted from sustainable rattan, designed for maximum comfort and safety.', 'Contact us', ARRAY['acc-047']),
  ('acc-048', 'Arched 3-Tier Rattan Shelf', 'accessories', 'A compact 3-tier arched display shelf suitable for organizing books, plants, or toiletries.', 'Contact us', ARRAY['acc-048']),
  ('acc-049', 'Standing Rattan Clothing Rack', 'accessories', 'A freestanding clothes rack made from sturdy rattan, complete with an upper hanging rod and lower storage shelf.', 'Contact us', ARRAY['acc-049']),
  ('acc-050', 'Rattan Vanity Table with Mirror', 'accessories', 'An exquisite bedroom vanity console table featuring an attached arch mirror and woven rattan drawers.', 'Contact us', ARRAY['acc-050']),
  ('acc-052', 'Wooden & Rattan Baby Play Gym', 'accessories', 'An interactive wooden baby activity gym accented with handcrafted rattan hanging sensory toys.', 'Contact us', ARRAY['acc-052']),
  ('acc-053', 'Circular Rattan Standing Shelf', 'accessories', 'A dramatic circular open-standing shelf unit framed in natural rattan for modern display.', 'Contact us', ARRAY['acc-053']),
  ('acc-054', 'Rattan Kids Clothes Rack', 'accessories', 'A child-sized freestanding garment rack constructed from durable natural rattan.', 'Contact us', ARRAY['acc-054']),
  ('acc-055', 'Rattan Lion Head Wall Mount', 'accessories', 'A fun and artistic lion head wall sculpture handwoven from natural fiber strands for kids rooms.', 'Contact us', ARRAY['acc-055']),
  ('acc-056', 'Rectangular Geometric Rattan Wall Mirror', 'accessories', 'A contemporary wall mirror framed in structured geometric rattan lattice work.', 'Contact us', ARRAY['acc-056']),
  ('acc-057', 'Round Rattan Wall Shelf with Towel Bar', 'accessories', 'A functional wall shelf unit featuring a woven display ledge and an integrated towel rack below.', 'Contact us', ARRAY['acc-057']),
  ('acc-058', 'Set of 3 Woven Wall Plates', 'accessories', 'A decorative set of three handwoven wall plates in varying sizes and organic geometric weaves.', 'Contact us', ARRAY['acc-058']),
  ('acc-059', 'Standing Rattan Lantern Set', 'accessories', 'A set of floor-standing rattan lanterns featuring inner candle holders to emit warm ambient light.', 'Contact us', ARRAY['acc-059']),
  ('acc-060', '2-Door Rattan Storage Cabinet', 'accessories', 'A freestanding storage cabinet featuring two doors fitted with breathable natural rattan webbing.', 'Contact us', ARRAY['acc-060']),
  ('acc-061', '2-Tier Rattan Bar Cart', 'accessories', 'A mobile two-tiered bar and serving cart crafted from rattan with castor wheels and beverage rails.', 'Contact us', ARRAY['acc-061']),
  ('acc-062', 'Curved Rattan Baby Crib', 'accessories', 'A gracefully contoured infant crib built with smooth rounded rattan spindles.', 'Contact us', ARRAY['acc-062']),
  ('acc-063', 'Pedestal Wicker Urn Planters Set', 'accessories', 'A set of raised pedestal urn planters handwoven from sturdy all-weather wicker.', 'Contact us', ARRAY['acc-063']),
  ('acc-064', 'Rattan Wall Hanger with Multi-Hooks', 'accessories', 'An extended wall-mounted organizer rack fitted with multiple sturdy rattan peg hooks.', 'Contact us', ARRAY['acc-064']),
  ('acc-065', 'Full-Length Arched Rattan & Cane Mirror', 'accessories', 'A tall arched dressing mirror accented with natural cane webbing along its outer border.', 'Contact us', ARRAY['acc-065']),
  ('acc-066', 'Large Rectangular Rattan Wall Mirror', 'accessories', 'A substantial wall mirror encased in a broad, heavy-weave natural rattan frame.', 'Contact us', ARRAY['acc-066']),
  ('acc-067', 'Oval Sunburst Rattan Mirror', 'accessories', 'An elongated oval mirror surrounded by an eye-catching radiating rattan sunburst motif.', 'Contact us', ARRAY['acc-067']),
  ('acc-068', 'Rattan Webbing Nightstand with Drawer', 'accessories', 'A modern bedside table featuring an open lower shelf and a drawer front styled in cane webbing.', 'Contact us', ARRAY['acc-068']),
  ('acc-069', 'Dark Wood Rattan Cane Side Table', 'accessories', 'A dark-stained solid timber side table featuring inset natural cane webbing accents.', 'Contact us', ARRAY['acc-069']),
  ('acc-070', '3-Tier Rattan Corner Shelf', 'accessories', 'A space-saving 3-tier corner shelf unit designed to optimize room corners with natural texture.', 'Contact us', ARRAY['acc-070']),
  ('acc-071', 'Round Wall Mirror with Brass Frame', 'accessories', 'A round accent mirror combining sleek metallic brass trim with a outer woven rattan frame.', 'Contact us', ARRAY['acc-071']),
  ('acc-072', 'Round Layered Rattan Wall Mirror', 'accessories', 'A multi-layered circular wall mirror featuring dimensional concentric rattan ring borders.', 'Contact us', ARRAY['acc-072']),
  ('acc-073', 'Arched Rattan Toddler Bed / Daybed', 'accessories', 'A charming toddler daybed constructed with arched rattan headboard and footboard frames.', 'Contact us', ARRAY['acc-073']),
  ('acc-074', 'Rattan Rocking Horse Toy', 'accessories', 'A nostalgic heirloom-quality rocking horse toy handcrafted entirely from sturdy natural rattan.', 'Contact us', ARRAY['acc-074']),
  ('acc-075', 'Llama-Shaped Rattan Storage Basket', 'accessories', 'A whimsical freestanding llama-shaped basket that serves as both a toy organizer and room decor.', 'Contact us', ARRAY['acc-075']),
  ('acc-076', 'Rattan 3-Tier Basket Drawer Chest', 'accessories', 'A vertical organizer unit holding three removable handwoven wicker storage basket drawers.', 'Contact us', ARRAY['acc-076']),
  ('acc-077', 'Rattan 2-Tier Drawer Nightstand', 'accessories', 'A compact two-drawer bedside table with natural woven rattan drawer panels.', 'Contact us', ARRAY['acc-077']),
  ('acc-078', 'Rectangular Rattan Wall Mirror', 'accessories', 'A clean-lined rectangular wall mirror framed in bound parallel rattan poles.', 'Contact us', ARRAY['acc-078']),
  ('acc-079', 'Cross-Base Rattan Accent Chair', 'accessories', 'An accent vanity chair featuring an intricate rattan weave seat on a geometric cross base.', 'Contact us', ARRAY['acc-079']),
  ('acc-080', 'Arched Rattan & Cane Floor Mirror', 'accessories', 'A tall floor-standing arch mirror decorated with fine cane webbing panel highlights.', 'Contact us', ARRAY['acc-080']),
  ('acc-081', 'Moroccan Arch Rattan Wall Mirror', 'accessories', 'An exotic wall mirror inspired by Moroccan architecture, framed in detailed bent rattan.', 'Contact us', ARRAY['acc-081']),
  ('acc-082', 'Decorative Arch Wicker Mirror', 'accessories', 'An arched accent mirror framed in densely handwoven, lightweight natural wicker.', 'Contact us', ARRAY['acc-082']),
  ('acc-083', 'Rattan Webbing Headboard', 'accessories', 'A queen-size bed headboard panel upholstered in durable, breathable natural cane webbing.', 'Contact us', ARRAY['acc-083']),
  ('acc-084', 'Arched Spindle Rattan Headboard', 'accessories', 'An open-work arched headboard featuring vertical rattan spindles for light, airy bedroom aesthetics.', 'Contact us', ARRAY['acc-084']),
  ('acc-085', 'Peacock Fan Rattan Headboard', 'accessories', 'A dramatic headboard featuring an ornate peacock-inspired radiating fan pattern.', 'Contact us', ARRAY['acc-085']),
  ('acc-086', 'Standing Wicker Storage Cabinet with Baskets', 'accessories', 'A timber frame storage unit outfitted with multiple deep pull-out wicker baskets.', 'Contact us', ARRAY['acc-086']),
  ('acc-087', 'Standing Rattan Floor Vases Set', 'accessories', 'A duo of decorative floor-standing vases woven from natural rattan strands.', 'Contact us', ARRAY['acc-087']),
  ('acc-088', 'Tall Rattan Floor Vases Set with Pampas', 'accessories', 'Tall, slim floor vases crafted from rattan, perfectly styled for holding dried pampas grass.', 'Contact us', ARRAY['acc-088']),
  ('acc-089', 'Spoke-Designed Round Rattan Mirror', 'accessories', 'A round mirror set within a bicycle-spoke style framework of slender rattan rods.', 'Contact us', ARRAY['acc-089']),
  ('acc-090', 'Radial Rattan Wall Mirror', 'accessories', 'A decorative circular wall mirror boasting a dense radial burst of natural rattan reeds.', 'Contact us', ARRAY['acc-090']),
  ('acc-091', 'Rustic Driftwood Tree Table Decor', 'accessories', 'An artistic tabletop sculpture assembled from naturally weathered marine driftwood pieces.', 'Contact us', ARRAY['acc-091']),
  ('acc-092', 'Rustic Driftwood Anchor Wall Decor', 'accessories', 'A coastal-style anchor wall art sculpture constructed entirely from natural reclaimed driftwood.', 'Contact us', ARRAY['acc-092']),
  ('acc-093', 'Rustic Wooden Log Table Decor', 'accessories', 'A natural slice of solid timber polished and finished as a rustic centerpiece display block.', 'Contact us', ARRAY['acc-093']),
  ('acc-094', 'Pyramid Floating Wall Shelves', 'accessories', 'Geometrically structured pyramid-shaped wall shelves crafted from solid wood accents.', 'Contact us', ARRAY['acc-094']),
  ('acc-095', 'Coastal Wooden Fish Sculpture', 'accessories', 'A hand-carved solid timber fish figurine mounted on a sturdy display stand.', 'Contact us', ARRAY['acc-095']),
  ('acc-096', 'Standing Wooden Star Statues Set', 'accessories', 'A decorative set of star-shaped wooden tabletop statues with a distressed rustic finish.', 'Contact us', ARRAY['acc-096']),
  ('acc-097', 'Rustic Handcarved Wooden Bowl Set', 'accessories', 'A pair of artisanal, hand-carved solid teak wood decorative bowls with natural graining.', 'Contact us', ARRAY['acc-097']),
  ('acc-098', 'Handcarved Wooden Mushroom Decor Set', 'accessories', 'A cute set of hand-carved timber mushroom figurines for shelf or desk decoration.', 'Contact us', ARRAY['acc-098']),
  ('acc-099', 'Circular Rattan Standing Bookshelf', 'accessories', 'A large round freestanding bookshelf constructed with outer rattan rims and flat wood display shelves.', 'Contact us', ARRAY['acc-099']),
  ('acc-100', 'Standing Wooden Heart Statues Set', 'accessories', 'A set of hand-carved wooden heart statues on metal stands, showcasing organic wood grain texture.', 'Contact us', ARRAY['acc-100']),
  ('acc-101', 'Full-Length Rectangular Woven Frame Mirror', 'accessories', 'A large floor dressing mirror enclosed in a broad, textured woven natural fiber frame.', 'Contact us', ARRAY['acc-101']),

  -- B. Basket Ware (10 items)
  ('b-001', 'Tall Curved Rattan Floor Vase with Mat Base', 'basket-ware', 'A tall floor-standing decorative rattan vase featuring a gently flared neck and a stable woven mat base.', 'Contact us', ARRAY['b-001']),
  ('b-002', 'Round Wicker Storage Baskets with Handles (Set of 2)', 'basket-ware', 'A pair of versatile round storage baskets handwoven from wicker with integrated carrying handles.', 'Contact us', ARRAY['b-002']),
  ('b-003', 'Heavy Woven Seagrass Storage Baskets Set', 'basket-ware', 'A set of heavy-duty storage baskets woven from durable natural seagrass, built for daily household organization.', 'Contact us', ARRAY['b-003']),
  ('b-004', 'Woven Storage Basket Set with Lids & Fabric Lining', 'basket-ware', 'Lidded wicker storage baskets fitted with removable, washable fabric liners to protect delicate stored items.', 'Contact us', ARRAY['b-004']),
  ('b-005', 'Whitewashed Woven Bamboo Laundry Hampers with Lids', 'basket-ware', 'Tall bamboo laundry hampers featuring a stylish whitewashed finish and fitted woven lids.', 'Contact us', ARRAY['b-005']),
  ('b-006', 'Square Wicker Nesting Baskets with Handles (Set of 3)', 'basket-ware', 'A set of three square wicker storage baskets designed to nest neatly inside one another when not in use.', 'Contact us', ARRAY['b-006']),
  ('b-007', 'Minimalist Fine-Woven Standing Rattan Vases', 'basket-ware', 'Sleek, tightly-woven floor-standing rattan vases that add refined organic texture to quiet corners.', 'Contact us', ARRAY['b-007']),
  ('b-008', 'Rustic Thick Woven Willow Baskets (Set of 2)', 'basket-ware', 'Sturdy utility baskets handwoven from thick natural willow branches, featuring rugged carrying handles.', 'Contact us', ARRAY['b-008']),
  ('b-009', 'Chevron Pattern Wicker Laundry Hampers (Set of 3)', 'basket-ware', 'A trio of tall laundry hampers decorated with stylish two-tone chevron weave patterns.', 'Contact us', ARRAY['b-009']),
  ('b-010', 'Rectangular Wicker Storage Baskets with Built-in Handles (Set of 3)', 'basket-ware', 'Practical rectangular organization baskets with inset hand holds, perfect for shelf and closet storage.', 'Contact us', ARRAY['b-010']),

  -- C. Bistro Chair (9 items)
  ('bc-001', 'French Bistro Rattan Dining Chair', 'chair-bench', 'A classic Parisian-style dining chair crafted from durable bent rattan with a colorful all-weather weave.', 'Contact us', ARRAY['bc-001']),
  ('bc-002', 'Black & White Woven Rattan Armchair with Curved Legs', 'chair-bench', 'A French cafe armchair featuring a striking black and white geometric weave and bentwood rattan legs.', 'Contact us', ARRAY['bc-002']),
  ('bc-003', 'Patterned French Bistro Dining Chairs Set', 'chair-bench', 'A set of bistro dining chairs showcasing traditional woven diamond patterns over a bent rattan frame.', 'Contact us', ARRAY['bc-003']),
  ('bc-004', 'Patterned Woven Rattan Cafe Chairs Pair', 'chair-bench', 'A pair of lightweight cafe chairs featuring comfortable woven resin seats and sturdy natural rattan legs.', 'Contact us', ARRAY['bc-004']),
  ('bc-005', 'Black & White Diamond-Weave Bistro Chair', 'chair-bench', 'A bistro dining chair highlighted by an intricate black-and-white diamond pattern across the seat and back.', 'Contact us', ARRAY['bc-005']),
  ('bc-006', 'Red & Black Chevron Bistro Dining Chair', 'chair-bench', 'A vibrant cafe chair featuring a bold red and black chevron weave on a durable bentwood rattan frame.', 'Contact us', ARRAY['bc-006']),
  ('bc-007', 'Round-Back French Bistro Chair', 'chair-bench', 'A round-back patio dining chair woven with synthetic rattan fibers designed to resist outdoor wear.', 'Contact us', ARRAY['bc-007']),
  ('bc-008', 'Black & White Chevron Bistro Dining Chair', 'chair-bench', 'A timeless French bistro chair styled with a crisp black and white chevron patterned backrest.', 'Contact us', ARRAY['bc-008']),
  ('bc-009', 'Black & White Chevron Bistro Dining Chair (Variant 2)', 'chair-bench', 'An alternative variant of the classic chevron bistro chair, featuring a wider seat pan and reinforced cross-bracing.', 'Contact us', ARRAY['bc-009']),

  -- D. Chair Indoor (57 items)
  ('ch-001', 'Modern Rounded Seagrass Accent Chair', 'chair-bench', 'A rounded accent chair tightly woven from natural seagrass, providing dense texture and plush seating comfort.', 'Contact us', ARRAY['ch-001']),
  ('ch-002', 'Rustic Wicker Patio Accent Chair', 'chair-bench', 'A comfortable accent chair constructed with a thick wicker weave and an ergonomic sloping backrest.', 'Contact us', ARRAY['ch-002']),
  ('ch-003', 'Blush Pink Rattan Rocking Chair', 'chair-bench', 'A playful nursery rocking chair finished in a soft blush pink hue over a bent rattan structure.', 'Contact us', ARRAY['ch-003']),
  ('ch-004', 'Arched Spindle Rattan Dining Chair', 'chair-bench', 'A lightweight dining chair featuring an arched top rail and classic vertical rattan spindle backrest.', 'Contact us', ARRAY['ch-004']),
  ('ch-005', 'High-Back Wicker Bucket Armchair', 'chair-bench', 'A deep-seating bucket armchair with an elevated high backrest woven entirely from natural wicker.', 'Contact us', ARRAY['ch-005']),
  ('ch-006', 'Bentwood Rattan Spindle Armchair', 'chair-bench', 'An elegant lounge chair showcasing expertly steam-bent rattan curves and vertical back spindles.', 'Contact us', ARRAY['ch-006']),
  ('ch-007', 'Bentwood Rattan Spindle Armchair (Variant 2)', 'chair-bench', 'A variation of the classic bentwood armchair featuring lower profile armrests and wider seat dimensions.', 'Contact us', ARRAY['ch-007']),
  ('ch-008', 'Spindle-Back Rattan Tub Chair with Cushion', 'chair-bench', 'A tub-shaped accent armchair with vertical rattan spindles, completed with a soft white linen cushion.', 'Contact us', ARRAY['ch-008']),
  ('ch-010', 'Geometric Bamboo-style Rattan Chair', 'chair-bench', 'A unique dining chair featuring structural rattan joinery designed to mimic natural bamboo nodes.', 'Contact us', ARRAY['ch-010']),
  ('ch-011', 'Peacock Fan-Back Rattan Accent Chair', 'chair-bench', 'An eye-catching accent chair featuring a dramatic fan-shaped peacock backrest handwoven from rattan.', 'Contact us', ARRAY['ch-011']),
  ('ch-014', 'Geometric Cane Webbing Armchair', 'chair-bench', 'A modern armchair featuring clean angular timber frames inlaid with breathable natural cane webbing.', 'Contact us', ARRAY['ch-014']),
  ('ch-015', 'Spindle-Back Bentwood Rattan Armchair', 'chair-bench', 'A graceful living room armchair with sweeping bentwood arms and a supportive spindle back.', 'Contact us', ARRAY['ch-015']),
  ('ch-016', 'Rustic Curved Rattan Armchair', 'chair-bench', 'A rustic armchair crafted from thick natural rattan poles, featuring an organic curved silhouette.', 'Contact us', ARRAY['ch-016']),
  ('ch-017', 'Modern Black Wicker Wingback Chair', 'chair-bench', 'A bold wingback accent chair woven in matte black wicker with a contrasting plush white cushion.', 'Contact us', ARRAY['ch-017']),
  ('ch-018', 'Natural Rattan Wingback Accent Chair with Metal Base', 'chair-bench', 'A modern hybrid wingback chair combining natural rattan weaving with slim black iron legs.', 'Contact us', ARRAY['ch-018']),
  ('ch-020', 'Scandinavian Wooden Lounge Chair with Rattan Webbing', 'chair-bench', 'A minimalist Scandinavian-inspired lounge chair featuring a solid oak frame and cane webbing seat.', 'Contact us', ARRAY['ch-020']),
  ('ch-022', 'Black Frame Cane Webbing Accent Chair', 'chair-bench', 'A sleek contemporary chair featuring a black timber frame paired with natural woven cane mesh.', 'Contact us', ARRAY['ch-022']),
  ('ch-023', 'Round Woven Rattan Papasan Chair with Metal Base', 'chair-bench', 'A modern papasan lounge chair featuring a circular woven rattan bowl resting on a sturdy metal frame.', 'Contact us', ARRAY['ch-023']),
  ('ch-024', 'Black Wicker Rocking Chair with Wooden Runners', 'chair-bench', 'A stylish rocking chair featuring a matte black wicker seat mounted on smooth solid timber rockers.', 'Contact us', ARRAY['ch-024']),
  ('ch-025', 'Boho Curved Rattan Lounge Rocking Chair', 'chair-bench', 'A bohemian-inspired rocking chair boasting smooth flowing rattan curves and an extra deep seat.', 'Contact us', ARRAY['ch-025']),
  ('ch-026', 'Woven Rattan High Bar Stool with Metal Legs', 'chair-bench', 'A counter-height bar stool featuring a comfortable woven rattan seat pan supported by industrial steel legs.', 'Contact us', ARRAY['ch-026']),
  ('ch-027', 'Black Woven Rattan Dining Chair with Slim Legs', 'chair-bench', 'A modern dining chair constructed with black woven rattan over slim powder-coated metal legs.', 'Contact us', ARRAY['ch-027']),
  ('ch-030', 'Bamboo Lattice-Back Rattan Counter Stool', 'chair-bench', 'A counter-height stool featuring an intricate open lattice backrest crafted from natural rattan.', 'Contact us', ARRAY['ch-030']),
  ('ch-031', 'Black Scalloped Rattan Accent Chair with Cushion', 'chair-bench', 'A playful accent chair featuring scalloped backrest edges finished in an elegant black stain.', 'Contact us', ARRAY['ch-031']),
  ('ch-032', 'Curved Rattan Counter Stool with Metal Legs', 'chair-bench', 'A sleek kitchen counter stool boasting a contoured rattan shell on minimalist dark metal legs.', 'Contact us', ARRAY['ch-032']),
  ('ch-033', 'Modern Black Woven Chair with Sled Base', 'chair-bench', 'A contemporary side chair featuring a black woven fiber body resting on a modern steel sled frame.', 'Contact us', ARRAY['ch-033']),
  ('ch-034', 'Classic Natural Rattan Rocking Chair', 'chair-bench', 'A timeless rocking chair crafted entirely from sturdy natural rattan with integrated armrests.', 'Contact us', ARRAY['ch-034']),
  ('ch-035', 'Peacock Petal-Back Rattan Dining Chair', 'chair-bench', 'A decorative dining chair featuring a backrest shaped like peacock feather petals.', 'Contact us', ARRAY['ch-035']),
  ('ch-036', 'High-Back Woven Wicker Armchair with Cushion', 'chair-bench', 'A cozy, high-backed armchair woven from fine wicker strands, complete with a fitted seat cushion.', 'Contact us', ARRAY['ch-036']),
  ('ch-038', 'Natural Rattan Curved Back Dining Chair', 'chair-bench', 'An ergonomic dining chair featuring a curved backrest that hugs the body, made of natural rattan.', 'Contact us', ARRAY['ch-038']),
  ('ch-039', 'Curved Spindle Rattan Armchair with Metal Frame', 'chair-bench', 'An industrial-boho armchair combining natural rattan vertical spindles with a black iron frame.', 'Contact us', ARRAY['ch-039']),
  ('ch-040', 'Dark Wicker High-Back Rocking Chair', 'chair-bench', 'A traditional rocking chair finished in a dark stain, featuring an elevated supportive backrest.', 'Contact us', ARRAY['ch-040']),
  ('ch-041', 'Minimalist Woven Rattan Club Chair', 'chair-bench', 'A low-profile club armchair featuring a thick, boxy natural rattan weave and plush seat cushion.', 'Contact us', ARRAY['ch-041']),
  ('ch-042', 'White Woven Resin Rattan Armchair', 'chair-bench', 'A crisp white all-weather resin rattan armchair suitable for both sunrooms and covered patios.', 'Contact us', ARRAY['ch-042']),
  ('ch-043', 'High-Back Dark Wicker Dining Chair with Cushion', 'chair-bench', 'A formal dining chair showcasing a tall dark wicker backrest and comfortable padded seat cushion.', 'Contact us', ARRAY['ch-043']),
  ('ch-046', 'Spindle Bentwood Rattan Lounge Armchair', 'chair-bench', 'A lounge chair featuring continuous bentwood rattan arms and open vertical back spindles.', 'Contact us', ARRAY['ch-046']),
  ('ch-047', 'French Bistro Woven Rattan High Bar Stool', 'chair-bench', 'A tall counter stool styled after French bistro furniture, featuring woven seat paneling.', 'Contact us', ARRAY['ch-047']),
  ('ch-049', 'Classic Pastel Rattan Side Chair with Cane Seat', 'chair-bench', 'A charming side chair painted in a soft pastel tone with an authentic woven cane webbing seat.', 'Contact us', ARRAY['ch-049']),
  ('ch-050', 'Dark Brown Spindle-Back Rattan Bar Stool', 'chair-bench', 'A dark brown high-top bar stool crafted with a supportive rattan spindle back and footrest.', 'Contact us', ARRAY['ch-050']),
  ('ch-052', 'Arch-Back Rattan Dining Chair', 'chair-bench', 'A sleek dining chair showcasing an arched top frame and vertical rattan weaving.', 'Contact us', ARRAY['ch-052']),
  ('ch-053', 'Grey Woven Wicker Armchair with Cushion', 'chair-bench', 'A modern armchair woven from grey-washed wicker fibers, complete with an off-white seat cushion.', 'Contact us', ARRAY['ch-053']),
  ('ch-054', 'Black Spindle Rattan Accent Chair with Geometric Base', 'chair-bench', 'A modern accent chair featuring black rattan spindles set over an eye-catching geometric base.', 'Contact us', ARRAY['ch-054']),
  ('ch-057', 'Black Bentwood Rattan Armchair', 'chair-bench', 'A dramatic arm chair hand-bent from solid rattan poles and finished in sleek matte black.', 'Contact us', ARRAY['ch-057']),
  ('ch-058', 'Traditional Handwoven Natural Fiber Chair', 'chair-bench', 'A classic dining chair constructed with a solid wooden frame and a handwoven natural cord seat.', 'Contact us', ARRAY['ch-058']),
  ('ch-059', 'Natural Rattan Papasan Chair with Plush Cushion', 'chair-bench', 'A traditional round papasan chair with a thick, plush tufted cushion resting in a sturdy rattan bowl.', 'Contact us', ARRAY['ch-059']),
  ('ch-060', 'Spindle Frame Rattan Box Armchair', 'chair-bench', 'A modern boxy lounge chair featuring straight rattan spindle walls and thick fabric cushions.', 'Contact us', ARRAY['ch-060']),
  ('ch-061', 'Classic Oval-Back Rattan Dining Armchair with Cushion', 'chair-bench', 'An elegant dining armchair featuring an oval cane-webbed backrest and upholstered seat.', 'Contact us', ARRAY['ch-061']),
  ('ch-062', 'High-Back Rattan Wingback Chair with Tufted Cushion', 'chair-bench', 'A luxurious wingback chair with intricate rattan weave side panels and a tufted seat cushion.', 'Contact us', ARRAY['ch-062']),
  ('ch-063', 'Spindle-Back Curved Rattan Tub Chair with Cushion', 'chair-bench', 'A tub chair boasting a smooth semi-circular curved backrest filled with vertical rattan rods.', 'Contact us', ARRAY['ch-063']),
  ('ch-064', 'Spindle Woven Rattan Bucket Chair with Metal Legs', 'chair-bench', 'A bucket seat chair featuring vertical rattan weaving supported by hairpin metal legs.', 'Contact us', ARRAY['ch-064']),
  ('ch-065', 'Classic Bentwood Rattan Armchair', 'chair-bench', 'A traditional living room armchair featuring flowing bentwood armrests and durable rattan construction.', 'Contact us', ARRAY['ch-065']),
  ('ch-068', 'High-Back Woven Wicker Settee Bench', 'chair-bench', 'A two-person seating bench featuring a high wicker backrest, perfect for entryways or dining tables.', 'Contact us', ARRAY['ch-068']),
  ('ch-069', 'Rounded Bentwood Rattan Dining Armchair with Cushion', 'chair-bench', 'A cozy dining chair with a continuous rounded bentwood frame and padded cushion.', 'Contact us', ARRAY['ch-069']),
  ('ch-070', 'Traditional Curved Rattan High-Back Armchair', 'chair-bench', 'A high-backed traditional lounge armchair with sweeping armrests handcrafted from solid rattan.', 'Contact us', ARRAY['ch-070']),

  -- E. Lounge and Day Bed (15 items)
  ('ld-001', 'White All-Weather Wicker Sun Lounger', 'lounge-daybed', 'An adjustable outdoor sun lounger handwoven from white all-weather resin wicker.', 'Contact us', ARRAY['ld-001']),
  ('ld-002', 'Dark Brown Curved Rattan Chaise Lounge', 'lounge-daybed', 'An ergonomically contoured chaise lounge made from dark brown rattan for poolside relaxation.', 'Contact us', ARRAY['ld-002']),
  ('ld-003', 'Round Outdoor Wicker Daybed with Retractable Canopy', 'lounge-daybed', 'A luxurious circular outdoor daybed featuring a retractable shade canopy and plush cushions.', 'Contact us', ARRAY['ld-003']),
  ('ld-004', 'Modern Striped Cushion Sun Lounger with Aluminum Frame', 'lounge-daybed', 'A contemporary pool lounger built on a rust-proof aluminum frame with striped all-weather padding.', 'Contact us', ARRAY['ld-004']),
  ('ld-005', 'Standing Rattan Egg Lounge Chair with Plush Cushion', 'lounge-daybed', 'A cozy cocoon egg-shaped lounge chair supported by a sturdy metal base with deep cushions.', 'Contact us', ARRAY['ld-005']),
  ('ld-006', 'Half-Moon Outdoor Wicker Daybed with Blue Cushions', 'lounge-daybed', 'A unique half-moon shaped outdoor daybed outfitted with vibrant blue moisture-resistant cushions.', 'Contact us', ARRAY['ld-006']),
  ('ld-007', 'Circular Rattan Canopy Daybed', 'lounge-daybed', 'A large round resort-style daybed with an integrated overhead woven rattan canopy.', 'Contact us', ARRAY['ld-007']),
  ('ld-008', 'Circular Outdoor Rattan Sunbed with Pillows', 'lounge-daybed', 'A spacious circular outdoor sunbed complete with multiple throw pillows for ultimate comfort.', 'Contact us', ARRAY['ld-008']),
  ('ld-009', 'Modern Spindle-Back Outdoor Sofa Daybed with Blue Cushions', 'lounge-daybed', 'A modern outdoor sofa daybed featuring a spindle backrest and deep ocean-blue cushions.', 'Contact us', ARRAY['ld-009']),
  ('ld-010', 'Wooden Frame Outdoor Canopy Daybed with Curtains', 'lounge-daybed', 'A luxury teak-framed canopy daybed complete with sheer outdoor privacy curtains.', 'Contact us', ARRAY['ld-010']),
  ('ld-011', 'Rustic Outdoor Poolside Chaise Lounge', 'lounge-daybed', 'A rustic chaise lounge crafted from thick natural rattan poles with an adjustable backrest.', 'Contact us', ARRAY['ld-011']),
  ('ld-012', 'Dark Brown All-Weather Wicker Chaise Lounge', 'lounge-daybed', 'A durable sun lounger woven in rich dark brown synthetic wicker, ideal for patio sunbathing.', 'Contact us', ARRAY['ld-012']),
  ('ld-013', 'Modern Aluminum Sun Lounger with Teak Armrests', 'lounge-daybed', 'A sleek contemporary sunbed featuring a powder-coated aluminum frame and natural teak arm accents.', 'Contact us', ARRAY['ld-013']),
  ('ld-014', 'Black Metal Frame Chaise Lounge with Off-White Cushion', 'lounge-daybed', 'A minimalist outdoor lounger with a slim black metal frame and thick off-white padding.', 'Contact us', ARRAY['ld-014']),
  ('ld-015', 'Modern Metal Frame Sun Lounger with Thick Cushion', 'lounge-daybed', 'An adjustable metal sunbed featuring an ultra-thick cushion for poolside comfort.', 'Contact us', ARRAY['ld-015']),

  -- F. Lounge Indoor (25 items)
  ('li-001', 'Sculptural Full Woven Rattan Armchair with Cushion', 'lounge-daybed', 'A dramatic sculptural armchair featuring a continuous handwoven rattan shell and plush seat cushion.', 'Contact us', ARRAY['li-001']),
  ('li-002', 'Spindle-Back Curved Rattan Daybed Bench', 'lounge-daybed', 'A charming indoor daybed bench styled with vertical rattan back spindles and a long seat cushion.', 'Contact us', ARRAY['li-002']),
  ('li-003', 'Woven Rattan Arm Sofa Daybed with Cushions', 'lounge-daybed', 'A multi-functional indoor sofa daybed featuring thick woven rattan side arms and deep seating.', 'Contact us', ARRAY['li-003']),
  ('li-004', 'Rustic Teak & Bamboo Spindle-Back Bench with Cushion', 'lounge-daybed', 'A sturdy indoor bench combining a solid teak wood frame with a bamboo spindle backrest.', 'Contact us', ARRAY['li-004']),
  ('li-005', 'Bamboo & Rattan Framed Daybed Sofa with Cushions', 'lounge-daybed', 'A natural bamboo and rattan sofa bed designed for relaxing indoor lounges or sunrooms.', 'Contact us', ARRAY['li-005']),
  ('li-006', 'Full Woven Seagrass Armchair with Cushions', 'lounge-daybed', 'A heavy-duty lounge armchair completely encased in textured handwoven natural seagrass.', 'Contact us', ARRAY['li-006']),
  ('li-007', 'Traditional High-Back Woven Wicker Loveseat', 'lounge-daybed', 'A classic two-seater wicker loveseat featuring a tall supportive backrest and comfortable seat pad.', 'Contact us', ARRAY['li-007']),
  ('li-008', 'Bamboo Spindle Frame Daybed Sofa with Cushion', 'lounge-daybed', 'A airy daybed sofa featuring a lightweight bamboo spindle frame and soft beige upholstery.', 'Contact us', ARRAY['li-008']),
  ('li-010', 'Traditional Curved Rattan Daybed Bench', 'lounge-daybed', 'A gracefully curved indoor daybed crafted from steam-bent natural rattan poles.', 'Contact us', ARRAY['li-010']),
  ('li-011', 'Modern Woven Cane 2-Seater Lounge Sofa', 'lounge-daybed', 'A sleek modern 2-seater couch featuring breathable natural cane webbing side panels.', 'Contact us', ARRAY['li-011']),
  ('li-012', 'Double Rattan Mamasan Chair with Tufted Cushion', 'lounge-daybed', 'An oval double-capacity mamasan chair featuring a wide rattan bowl frame and plush cushion.', 'Contact us', ARRAY['li-012']),
  ('li-013', 'Lattice-Back Rattan Accent Chair with Cushion', 'lounge-daybed', 'An elegant lounge chair showcasing an open geometric lattice pattern woven across the backrest.', 'Contact us', ARRAY['li-013']),
  ('li-014', 'White Painted Rattan Daybed Sofa with Black Seat Cushion', 'lounge-daybed', 'A striking crisp white rattan daybed sofa contrasted with a sleek black cushion.', 'Contact us', ARRAY['li-014']),
  ('li-015', 'Peacock Fan-Back Rattan Bench with Black Cushion', 'lounge-daybed', 'A grand peacock-style two-seater bench with dramatic fan back detailing and dark cushioning.', 'Contact us', ARRAY['li-015']),
  ('li-016', 'Spindle-Back Rattan Toddler Daybed Bed Frame', 'lounge-daybed', 'A charming toddler bed frame built with safety-focused rattan side spindles.', 'Contact us', ARRAY['li-016']),
  ('li-017', 'Curved Woven Rattan Daybed Bench with Cushion', 'lounge-daybed', 'An organic curved daybed bench featuring fine woven rattan trim and a custom fitted mattress pad.', 'Contact us', ARRAY['li-017']),
  ('li-018', 'Diamond Lattice-Back Rattan Accent Chair with Cushions', 'lounge-daybed', 'A statement lounge chair decorated with a diamond-patterned lattice weave across its back frame.', 'Contact us', ARRAY['li-018']),
  ('li-019', 'Spindle-Back Curved Rattan Settee Bench with Cushion', 'lounge-daybed', 'A slender settee bench with curved armrests and vertical back spindles, ideal for hallway seating.', 'Contact us', ARRAY['li-019']),
  ('li-020', 'Double Papasan Rattan Lounge Loveseat', 'lounge-daybed', 'A wide two-person papasan loveseat resting on a sturdy double-ring rattan base.', 'Contact us', ARRAY['li-020']),
  ('li-021', 'Ornate Peacock-Style Rattan Bench Settee', 'lounge-daybed', 'An elaborate peacock-inspired bench showcasing intricate artisan swirl-work made of natural rattan.', 'Contact us', ARRAY['li-021']),
  ('li-023', 'High-Back Spindle Oval Peacock Rattan Chair', 'lounge-daybed', 'A towering accent chair with an oval peacock backrest and vertical rattan detail lines.', 'Contact us', ARRAY['li-023']),
  ('li-024', 'Wide Oval Woven Peacock Rattan Armchair', 'lounge-daybed', 'An expansive peacock armchair featuring a wide oval backrest and rich woven accents.', 'Contact us', ARRAY['li-024']),
  ('li-026', 'Rounded High-Back Peacock Rattan Chair with Cushion', 'lounge-daybed', 'A classic peacock accent chair with a rounded halo backrest and soft white seat pad.', 'Contact us', ARRAY['li-026']),
  ('li-027', 'Circular Rattan Egg Lounge Chair with Cushions', 'lounge-daybed', 'A deep circular egg-style lounge chair that cradles the sitter with comfortable plush cushions.', 'Contact us', ARRAY['li-027']),

  -- G. Outdoor Chair (37 items)
  ('co-001', 'Nordic Wooden Armchair with Woven Rope Seat', 'chair-bench', 'A Nordic-style dining armchair featuring a smooth timber frame and durable woven rope seat.', 'Contact us', ARRAY['co-001']),
  ('co-002', 'Saddle-style Wooden Stool with Woven Seat', 'chair-bench', 'A backless saddle stool crafted from solid wood with an ergonomic woven cord seat top.', 'Contact us', ARRAY['co-002']),
  ('co-003', 'Solid Teak Stool with Woven Fiber Seat', 'chair-bench', 'A compact stool made from solid teak wood topped with tightly stretched weather-resistant fiber.', 'Contact us', ARRAY['co-003']),
  ('co-004', 'Minimalist Wooden Bench with Woven Cane Seat', 'chair-bench', 'A clean-lined entryway bench featuring a solid wood frame and woven cane seating surface.', 'Contact us', ARRAY['co-004']),
  ('co-005', 'Modern Woven Rope Dining Armchair with Cushion', 'chair-bench', 'A modern outdoor dining chair featuring weather-resistant rope weaving and a plush cushion.', 'Contact us', ARRAY['co-005']),
  ('co-006', 'Black Woven Mesh Metal Accent Armchair', 'chair-bench', 'An industrial accent chair featuring a black powder-coated metal frame and woven mesh seat.', 'Contact us', ARRAY['co-006']),
  ('co-007', 'Modern Black Woven Rope Dining Armchair', 'chair-bench', 'A sleek outdoor dining armchair woven with heavy-duty black synthetic rope.', 'Contact us', ARRAY['co-007']),
  ('co-008', 'Woven Rattan Scoop Lounge Chair with Metal Legs', 'chair-bench', 'A scoop-shaped rattan lounge seat mounted on slender, modern black iron legs.', 'Contact us', ARRAY['co-008']),
  ('co-009', 'Mid-Century Woven Rattan Dining Chair with Tapered Legs', 'chair-bench', 'A mid-century modern inspired dining chair with a woven rattan bucket seat and tapered legs.', 'Contact us', ARRAY['co-009']),
  ('co-010', 'Rustic Solid Wood Accent Stool', 'chair-bench', 'A rugged accent stool carved from solid natural timber, showcasing raw wood textures.', 'Contact us', ARRAY['co-010']),
  ('co-011', 'Rustic Solid Wood Console Table with Lower Shelf', 'table', 'A rustic hallway console table built from solid reclaimed timber with an integrated lower display shelf.', 'Contact us', ARRAY['co-011']),
  ('co-012', 'Farmhouse Natural Wood Entryway Bench', 'chair-bench', 'A sturdy farmhouse-style wooden bench designed for entryways or dining table seating.', 'Contact us', ARRAY['co-012']),
  ('co-013', 'Rustic Round Wooden Stool with Cross Base', 'chair-bench', 'A round solid wood stool supported by a classic four-point cross-brace leg design.', 'Contact us', ARRAY['co-013']),
  ('co-014', 'Modern Dark Gray Woven Rope Dining Armchair', 'chair-bench', 'A contemporary patio armchair wrapped in dark gray, UV-resistant synthetic rope.', 'Contact us', ARRAY['co-014']),
  ('co-015', 'Teak Frame Dining Armchair with Rope Back & Cushions', 'chair-bench', 'A premium outdoor dining chair combining a solid teak wood frame with nautical rope weaving.', 'Contact us', ARRAY['co-015']),
  ('co-016', 'Folding Wooden Directors Chair with Black Fabric', 'chair-bench', 'A portable folding director chair crafted from teak wood with durable black canvas seating.', 'Contact us', ARRAY['co-016']),
  ('co-017', 'Woven Rope Bucket Armchair with Gray Cushion', 'chair-bench', 'A bucket-style patio chair woven with thick grey rope and accompanied by a thick cushion.', 'Contact us', ARRAY['co-017']),
  ('co-018', 'White Frame Metal Dining Chair with Wooden Seat & Woven Back', 'chair-bench', 'A stylish outdoor chair featuring a white metal frame, wooden seat pan, and woven backrest.', 'Contact us', ARRAY['co-018']),
  ('co-019', 'Modern Aluminum Dining Armchair with Teak Armrests & Cushion', 'chair-bench', 'A rust-free aluminum dining chair elevated with natural teak wood armrest accents.', 'Contact us', ARRAY['co-019']),
  ('co-020', 'Dark Woven Rope Dining Armchair with Beige Cushion', 'chair-bench', 'An outdoor dining chair featuring dark woven rope paneling contrasted with a light beige cushion.', 'Contact us', ARRAY['co-020']),
  ('co-021', 'Gray Woven Rope Barrel Dining Chair with Light Gray Frame', 'chair-bench', 'A barrel-contoured dining chair featuring light gray metal legs and woven synthetic rope.', 'Contact us', ARRAY['co-021']),
  ('co-022', 'Natural Rattan Barrel Dining Armchair with Wooden Base', 'chair-bench', 'A cozy barrel armchair handcrafted from natural rattan with a sturdy solid wood leg base.', 'Contact us', ARRAY['co-022']),
  ('co-023', 'Orange Woven Cord Barrel Dining Chair with Cushion', 'chair-bench', 'A colorful patio chair wrapped in eye-catching orange woven cord for accent seating.', 'Contact us', ARRAY['co-023']),
  ('co-024', 'Dark Metal Frame Deep-Seating Dining Armchair with Cushions', 'chair-bench', 'A deep-seating outdoor armchair built on a heavy-duty metal frame with weather-proof cushions.', 'Contact us', ARRAY['co-024']),
  ('co-025', 'Wooden Frame Dining Armchair with Rope Back & Cushions', 'chair-bench', 'An elegant wooden patio dining chair featuring an intricate rope weave backrest.', 'Contact us', ARRAY['co-025']),
  ('co-026', 'Woven Cane Bar Stool with Black Metal Legs', 'chair-bench', 'A tall counter stool featuring a comfortable woven cane seat pan on tall steel legs.', 'Contact us', ARRAY['co-026']),
  ('co-027', 'Traditional Woven Rattan Bar Stool with Armrests', 'chair-bench', 'A classic high-top bar stool built with natural rattan legs, supportive armrests, and a woven seat.', 'Contact us', ARRAY['co-027']),
  ('co-028', 'Metal Frame Bar Stool with Woven Rope Back & Cushion', 'chair-bench', 'A modern metal bar stool featuring a woven rope backrest and padded seat cushion.', 'Contact us', ARRAY['co-028']),
  ('co-029', 'Wooden Frame Bar Stool with Cutout Metal Back & Cushion', 'chair-bench', 'A unique bar stool featuring a warm timber frame paired with a decorative metal backplate.', 'Contact us', ARRAY['co-029']),
  ('co-030', 'Round Woven Basket Lounge Chair with Cushion & Pillow', 'chair-bench', 'A bowl-shaped outdoor basket lounge chair outfitted with thick comfortable padding and throw pillow.', 'Contact us', ARRAY['co-030']),
  ('co-031', 'Modern Woven Rope Rocking Chair with Metal Base', 'chair-bench', 'A contemporary rocking chair combining weather-resistant rope weave with a smooth metal rocker frame.', 'Contact us', ARRAY['co-031']),
  ('co-032', 'Wooden Frame Lounge Chair with Black Woven Leather Seat', 'chair-bench', 'A modern lounge chair constructed from smooth timber and woven black leather straps.', 'Contact us', ARRAY['co-032']),
  ('co-033', 'Slatted Wooden Lounge Chair with Natural Woven Cord Seat', 'chair-bench', 'A relaxed low-slung lounge chair crafted from solid wood with woven natural cord detailing.', 'Contact us', ARRAY['co-033']),
  ('co-034', 'Curved Rattan Rocking Chair with Seat Cushion', 'hanging-chair', 'A smooth-rocking patio chair crafted from durable curved rattan with an included seat pad.', 'Contact us', ARRAY['co-034']),
  ('co-036', 'Hanging Rattan Basket Swing Chair with Beige Cushion', 'hanging-chair', 'A suspended rattan swing chair that hangs gracefully to offer relaxing motion and plush comfort.', 'Contact us', ARRAY['co-036']),
  ('co-037', 'Standing Wicker Hanging Egg Chair with Brown Cushion', 'hanging-chair', 'A freestanding egg swing chair featuring an all-weather wicker pod and heavy metal stand.', 'Contact us', ARRAY['co-037'])


    ('tbi-001', 'Round Rattan Coffee Table with Wooden Top', 'Table Indoor', 'A round rattan coffee table featuring a solid wooden top, blending natural textures with functional surface space.', 'Contact us', ARRAY['tbi-001']),
    ('tbi-002', 'Woven Water Hyacinth Bench with Wooden Legs', 'Table Indoor', 'A stylish bench made from woven water hyacinth supported by sturdy wooden legs, perfect for indoor seating.', 'Contact us', ARRAY['tbi-002']),
    ('tbi-003', 'Round Woven Rattan Coffee Table with Open Base', 'Table Indoor', 'A round coffee table featuring an intricate open woven rattan base for an airy and organic look.', 'Contact us', ARRAY['tbi-003']),
    ('tbi-004', 'Round Glass Top Coffee Table with Woven Natural Fiber Base', 'Table Indoor', 'A contemporary round coffee table combining a clear glass top with a textured natural fiber base.', 'Contact us', ARRAY['tbi-004']),
    ('tbi-005', 'Round Rattan Slatted Accent Stool', 'Table Indoor', 'A versatile round accent stool crafted with vertical rattan slats, suitable as a side table or seating.', 'Contact us', ARRAY['tbi-005']),
    ('tbi-006', 'Rectangular Rattan Coffee Table with Slatted Top', 'Table Indoor', 'A spacious rectangular coffee table constructed with a slatted rattan top and robust frame.', 'Contact us', ARRAY['tbi-006']),
    ('tbi-007', 'Round Rattan Coffee Table with Open Geometric Base', 'Table Indoor', 'An eye-catching round coffee table designed with an open geometric rattan pattern.', 'Contact us', ARRAY['tbi-007']),
    ('tbi-008', 'Round Dark Rattan Accent Stool with Loop Design', 'Table Indoor', 'A dark-stained round accent stool featuring elegant rattan loop patterns around the base.', 'Contact us', ARRAY['tbi-008']),
    ('tbi-009', 'Round Glass Top Coffee Table with Curved Rattan Base', 'Table Indoor', 'A stylish round coffee table with a tempered glass top set upon gracefully curved rattan legs.', 'Contact us', ARRAY['tbi-009']),
    ('tbi-010', 'Round Glass Top Coffee Table with Lower Shelf and Rattan Frame', 'Table Indoor', 'A practical round coffee table offering a glass top and an integrated lower storage shelf.', 'Contact us', ARRAY['tbi-010']),
    ('tbi-011', 'Round Woven Rattan Drum Coffee Table with Solid Top', 'Table Indoor', 'A drum-style coffee table featuring a fully woven rattan body topped with a smooth flat surface.', 'Contact us', ARRAY['tbi-011']),
    ('tbi-012', 'Round Glass Top Accent Table with Curved Rattan Base', 'Table Indoor', 'A compact glass-top accent table supported by an elegant swept rattan leg design.', 'Contact us', ARRAY['tbi-012']),
    ('tbi-013', 'Modern Wicker Center Table with Pedestal Base', 'Table Indoor', 'A modern center table crafted with woven wicker atop a central pedestal support.', 'Contact us', ARRAY['tbi-013']),
    ('tbi-014', 'Rectangular Rattan Console Table with Lower Shelf', 'Table Indoor', 'A slim rectangular console table made from rattan, featuring a lower shelf for additional display space.', 'Contact us', ARRAY['tbi-014']);
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  images = EXCLUDED.images;